### ISSUE TITLE
エクスペリメンタル: cssをno bundleで読み込む

### ISSUE THREAD

**Issue by monoharada** [monosus/super-static#50]
## 概要

- src内のcssファイルをbundleせず全て_global.tsxへlinkタグで挿入する
- 単一のcssについてui.css内にある
```css
.button {
  @layer ui.base {
    padding: calc(var(--line-height) / 4 * 1em) var(--font-size);
    border: 1px solid #fff;
    border-radius: var(--buton-border-radius);
    background-color: #000;
    color: #fff;
    font-size: var(--font-size);
    line-height: var(--line-height);
  }

  @layer ui.state {
    transition: filter 0.2s ease-in-out;

    @media (hover: hover) {
      &:hover {
        filter: invert(100%);
      }
    }
  }
}
```
などを参考に**cssファイルの書き方**を提供する。

- no bundle,モダンcssについてドキュメンテーションする
